'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SET_BACKGROUND_COLOR = exports.SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';
var DRAW_BACKGROUND_IMAGE = exports.DRAW_BACKGROUND_IMAGE = 'DRAW_BACKGROUND_IMAGE';
var DRAW_IMAGE_TASK = exports.DRAW_IMAGE_TASK = 'DRAW_IMAGE_TASK';
var DRAW_TEXT_TASK = exports.DRAW_TEXT_TASK = 'DRAW_TEXT_TASK';