export const SET_BACKGROUND_COLOR='SET_BACKGROUND_COLOR'
export const DRAW_BACKGROUND_IMAGE='DRAW_BACKGROUND_IMAGE'
export const DRAW_IMAGE_TASK='DRAW_IMAGE_TASK'
export const DRAW_TEXT_TASK='DRAW_TEXT_TASK'